### ISSUE TITLE
What's the *why*?

### ISSUE THREAD

**Issue by gunar** [nav-inc/nav-schema-architecture#1]
Hey @jdubray, generally it seems like this is an API-generating tool that takes a schema definition and generates GraphQL Objects for it. If, and that's a big if, I got that right, then I wonder if you've taken a look at what Hasura.io is doing, in which they take a database's schema and generate GraphQL queries and mutations off it. I'm sure I'm missing something but perhaps the analogy helps me understand NSA better.

**Comment by gunar** [comment]
Oh, and to make the title of the issue make sense, I feel like the _why_ of NSA should be incorporated into the README. It seems it contains the what and the how but it's missing the why which might've answered by question above.

**Comment by jdubray** [comment]
Hi Gunar, sorry, I just saw your comment. This is really about generating payload validation code (and schemas) at scale. It has nothing to do with GraphQL per se, except that we are reusing the two GraphQL DSLs: Schema and Queries.  The Schema is used to define the common data model of the data elements in the payloads (Entities and fields) and the Query DSL is used to define the payload structure pointing to the entities/field types giving a structural strength to the payload definition.

**Comment by gunar** [comment]
Very cool. That means you get access to all of the GraphQL toolkit and ecosystem out there.
